GET http://localhost:3000/routes

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "Route Toledo - Cascavel",
  "source_id": "ChIJYWo1on-V85QRUBuHw2H8qWA",
  "destination_id": "ChIJYU33xx7U85QRvF9a4OwyrOs"
}

###################
### Google Maps ###
###################

### Get place info by place id
GET http://localhost:3000/places?text=cascavel pr

### Get direction by two places
GET http://localhost:3000/directions?originId=ChIJp7SRyLOc85QRyAgfX3zkeJY&destinationId=ChIJdfUuJshW2ZQRsN9WdVbveMk