GET http://localhost:3000/routes

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "New route test",
  "source_id": "ChIJp7SRyLOc85QRyAgfX3zkeJY",
  "destination_id": "ChIJdfUuJshW2ZQRsN9WdVbveMk"
}

###################
### Google Maps ###
###################

### Get place info by place id
GET http://localhost:3000/places?text=itapoa sc

### Get direction by two places
GET http://localhost:3000/directions?originId=ChIJp7SRyLOc85QRyAgfX3zkeJY&destinationId=ChIJdfUuJshW2ZQRsN9WdVbveMk